[package]
name = "frozen"
version = "0.4.0"
authors = ["tux3 <barrdetwix@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
tokio = "0.2.0-alpha.6"
tokio-executor = "0.2.0-alpha.6"
tokio-net = "0.2.0-alpha.6"
tokio-timer = "0.3.0-alpha.6"
hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
hyper-tls = "0.4.0-alpha.4"
bytes = "0.4"
futures-preview = { version = "0.3.0-alpha" }
bincode = "1.2"
sodiumoxide = "0.2"
libsodium-sys = "0.2"
rpassword = "2.1"
blake2 = "0.8"
sha-1 = "0.8"
digest = "0.8"
zstd = "0.4"
pretty-bytes = "0.2"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
data-encoding = "2.1"
ctrlc = "3.1"
clamp = "= 0.1.0" # This is a left-pad-like dep, does not ever need to update
num_cpus = "1.10"
clap = "2"
leb128 = "0.2"
ignore-result = "0.2"
owning_ref = "0.3"
hashbrown = "0.6"
futures-intrusive = "0.2"
crossbeam = "0.7"
indicatif = "0.12"

[profile.release]
lto = true
incremental = false
codegen-units = 1
