[package]
name = "frozen"
version = "0.2.0"
authors = ["tux3 <barrdetwix@gmail.com>"]

[dependencies]
hyper = "0.10"
hyper-openssl = "0.2"
bincode = "0.8"
sodiumoxide = "0.0.14"
libsodium-sys = "0.0.14"
rpassword = "0.3"
blake2 = "0.5"
sha-1 = "0.3"
digest = "0.5"
zstd = "0.4"
pretty-bytes = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
data-encoding = "1.2"