[package]
name = "frozen"
version = "0.5.0"
authors = ["tux3 <barrdetwix@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
serde = {version = "1.0", features = ["derive"]}
tokio = { version = "0.2", features = ["macros", "rt-threaded", "signal"] }
zstd = { version = "0.5", features = ["tokio"] }
hyper = "0.13"
hyper-tls = "0.4"
futures = "0.3"
bytes = "0.5"
bincode = "1.2"
sodiumoxide = "0.2"
libsodium-sys = "0.2"
rpassword = "5.0"
blake2 = "0.9"
sha-1 = "0.9"
digest = "0.9"
serde_json = "1.0"
data-encoding = "2.1"
base64 = "0.12"
clamp = "= 0.1.0" # This is a left-pad-like dep, does not ever need to update
num_cpus = "1.10"
clap = "2"
leb128 = "0.2"
owning_ref = "0.4"
hashbrown = "0.9"
futures-intrusive = "0.3"
crossbeam = "0.7"
indicatif = "0.15"
tempfile = "3"

[profile.release]
lto = true
incremental = false
codegen-units = 1
