[package]
name = "frozen"
version = "0.1.0"
authors = ["tux3 <barrdetwix@gmail.com>"]

[dependencies]
hyper = "0.9"
rustc-serialize = "0.3"
bincode = "0.6.0"
sodiumoxide = "0.0.12"
rpassword = "0.3.0"
sha1 = "0.2.0"